package com.newsletter.model;

// Generated 29 sept. 2011 22:28:32 by Hibernate Tools 3.4.0.CR1

/**
 * Compteur generated by hbm2java
 */
public class Compteur implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String titremail;
	private String dateenvoie;
	private Integer nbenvoie;

	public Compteur() {
	}

	public Compteur(String titremail, String dateenvoie, Integer nbenvoie) {
		this.titremail = titremail;
		this.dateenvoie = dateenvoie;
		this.nbenvoie = nbenvoie;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitremail() {
		return this.titremail;
	}

	public void setTitremail(String titremail) {
		this.titremail = titremail;
	}

	public String getDateenvoie() {
		return this.dateenvoie;
	}

	public void setDateenvoie(String dateenvoie) {
		this.dateenvoie = dateenvoie;
	}

	public Integer getNbenvoie() {
		return this.nbenvoie;
	}

	public void setNbenvoie(Integer nbenvoie) {
		this.nbenvoie = nbenvoie;
	}

}
