package com.newsletter.model;

// Generated 29 sept. 2011 22:28:32 by Hibernate Tools 3.4.0.CR1

/**
 * EmailsTest generated by hbm2java
 */
public class EmailsTest implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private String email1;
	private String email2;
	private String email3;
	private String email4;
	private String email5;

	public EmailsTest() {
	}

	public EmailsTest(String email1, String email2, String email3,
                      String email4, String email5) {
		this.email1 = email1;
		this.email2 = email2;
		this.email3 = email3;
		this.email4 = email4;
		this.email5 = email5;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail1() {
		return this.email1;
	}

	public void setEmail1(String email1) {
		this.email1 = email1;
	}

	public String getEmail2() {
		return this.email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	public String getEmail3() {
		return this.email3;
	}

	public void setEmail3(String email3) {
		this.email3 = email3;
	}

	public String getEmail4() {
		return this.email4;
	}

	public void setEmail4(String email4) {
		this.email4 = email4;
	}

	public String getEmail5() {
		return this.email5;
	}

	public void setEmail5(String email5) {
		this.email5 = email5;
	}

}
