package com.newsletter.model;

// Generated 29 sept. 2011 22:28:32 by Hibernate Tools 3.4.0.CR1

/**
 * IpToCountry generated by hbm2java
 */
public class IpToCountry implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private IpToCountryId id;
	private String countryCode;
	private String countryCode3;
	private String countryName;

	public IpToCountry() {
	}

	public IpToCountry(IpToCountryId id, String countryCode3) {
		this.id = id;
		this.countryCode3 = countryCode3;
	}

	public IpToCountry(IpToCountryId id, String countryCode,
			String countryCode3, String countryName) {
		this.id = id;
		this.countryCode = countryCode;
		this.countryCode3 = countryCode3;
		this.countryName = countryName;
	}

	public IpToCountryId getId() {
		return this.id;
	}

	public void setId(IpToCountryId id) {
		this.id = id;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getCountryCode3() {
		return this.countryCode3;
	}

	public void setCountryCode3(String countryCode3) {
		this.countryCode3 = countryCode3;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

}
