package com.newsletter.model;

// Generated 29 sept. 2011 22:28:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * NewsLettersMail generated by hbm2java
 */
public class NewsLettersMail implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Date dateNews;
	private String titre;
	private String laPage;

	public NewsLettersMail() {
	}

	public NewsLettersMail(final Date _dateNews, final String _titre, final String _laPage) {
        super();
		this.dateNews = _dateNews;
		this.titre = _titre;
		this.laPage = _laPage;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDateNews() {
		return this.dateNews;
	}

	public void setDateNews(Date dateNews) {
		this.dateNews = dateNews;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getLaPage() {
		return this.laPage;
	}

	public void setLaPage(String laPage) {
		this.laPage = laPage;
	}

}
